# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96590c398565bb0725cef545506455ce"
name = "image-request"
handle = "image-request-1"
application_url = "https://mobility-msie-flu-indicated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mobility-msie-flu-indicated.trycloudflare.com/auth/callback",
  "https://mobility-msie-flu-indicated.trycloudflare.com/auth/shopify/callback",
  "https://mobility-msie-flu-indicated.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
