# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79878a016f8f1ac9b018f0daefe2f0f0"
name = "image-request"
handle = "image-request"
application_url = "https://separate-sky-era-screw.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://separate-sky-era-screw.trycloudflare.com/auth/callback",
  "https://separate-sky-era-screw.trycloudflare.com/auth/shopify/callback",
  "https://separate-sky-era-screw.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
